# Site settings
title: Shoplaw.com
email: your-email@domain.com
description: This is an online marketplace for legal services. We give you the price and specialty of lawyers near you, so you can choose wisely. Your lawyer search is easy with ShopLaw.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shoplaw.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
